<?php
// Implements hook_init()
function openfema_init () {

}

// Implements hook_menu()
function openfema_menu () {

    $items['vis_1'] = array(
        'title' => 'Fire Data chloropeth',
        'page callback' => 'openfema_chloropeth',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    $items['vis_2'] = array(
        'title' => 'Basic Bar',
        'page callback' => 'openfema_basic_bar',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    $items['vis_3'] = array(
        'title' => 'KY Zip',
        'page callback' => 'openfema_ky_zip',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    return $items;
}

function openfema_chloropeth() {

    $path = drupal_get_path('module', 'openfema');

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array('data_path' => $path.'/data/');

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/chloropeth.css');
    drupal_add_js($path.'/js/chloropeth.js',   array('scope' => 'footer'));

    $content = file_get_contents($path.'/html/chloropeth.html');

    return $content;
}

function openfema_basic_bar() {

    $path = drupal_get_path('module', 'openfema');

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array('data_path' => $path.'/data/');

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/basicbar.css');
    drupal_add_js($path.'/js/basicbar.js',   array('scope' => 'footer'));

    $content = file_get_contents($path.'/html/basicbar.html');

    return $content;
}

function openfema_ky_zip() {

    $path = drupal_get_path('module', 'openfema');

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array('data_path' => $path.'/data/');

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/ky_zip.css');
    drupal_add_js($path.'/js/ky_zip.js',   array('scope' => 'footer'));

    $content = file_get_contents($path.'/html/ky_zip.html');

    return $content;
}