<?php
// Implements hook_init()
function openfema_init () {

}

// Implements hook_menu()
function openfema_menu () {

    $items['vis_1'] = array(
        'title' => 'Fire Data chloropeth',
        'page callback' => 'openfema_chloropeth',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    $items['vis_2'] = array(
        'title' => 'US Zip',
        'page callback' => 'openfema_us_zip',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    $items['vis_3'] = array(
        'title' => 'KY Zip',
        'page callback' => 'openfema_ky_zip',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    $items['query'] = array(
        'title' => 'KY Zip Query',
        'page callback' => 'openfema_zip_query',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    return $items;
}

function openfema_chloropeth() {

    $path = drupal_get_path('module', 'openfema');

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array('data_path' => $path.'/data/');

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/chloropeth.css');
    drupal_add_js($path.'/js/chloropeth.js',   array('scope' => 'footer'));

    $output = '
        <div align="center" style="width:860px">
        <h2> Chloropeth</h2>
        </div>
        <container></container>';

    return $output;
}

function openfema_us_zip() {

    $path = drupal_get_path('module', 'openfema');

    $query = array();

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array(
        'data_path' => $path.'/data/',
        'data'      => openfema_zip_query($query)
    );

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    //drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/zip.css');
    drupal_add_js($path.'/js/us_zip.js',   array('scope' => 'footer'));

    $output = '
        <div align="center" style="width:860px">
        <h2>Fire Rate in US by zipcode</h2>
        </div>
        <div id="geo-map" align="center" style="width:860px"></div>';

    return $output;
}

function openfema_ky_zip() {

    $path = drupal_get_path('module', 'openfema');

    $query = array();
    $query['state'] = 'KY';
    //$query['zips']  = array('40003','40865','41014');

    // pass data to javascript
    $add_js = array();
    $add_js['openfema'] = array(
        'data_path' => $path.'/data/',
        'data'      => openfema_zip_query($query)
    );

    drupal_add_js($add_js, 'setting');

    // needed for D3, advanced sliders etc.
    drupal_add_library('addlibraries','d3.v3');
    //drupal_add_library('addlibraries','jQueryUI_1.9');

    drupal_add_css($path.'/css/zip.css');
    drupal_add_js($path.'/js/ky_zip.js',   array('scope' => 'footer'));

    $output = '
        <div align="center" style="width:860px">
        <h2>Fire Rate in KY by zipcode</h2>
        </div>
        <div id="geo-map" align="center" style="width:860px"></div>';

    return $output;
}

function openfema_zip_query( $query = array() ) {

    // Submit those variables to the server
    if ( $_GET['state'] || $_GET['zips'] ) {
        $query['state'] = $_GET['state'];
        $query['zips'] = $_GET['zips'];
    }

    $query['fields'] = array();
    $query['fields'][] = 'zip';
    $query['fields'][] = 'county';
    $query['fields'][] = 'state';
    $query['fields'][] = 'estimated_population';
    $query['fields'][] = 'TotalFires';
    $query['fields'][] = 'FiresOther';
    $query['fields'][] = 'StructureFires';
    $query['fields'][] = 'MobilPropAsStructFires';
    $query['fields'][] = 'VehicleFires';
    $query['fields'][] = 'NatVegitationFires';
    $query['fields'][] = 'OutsideRubbishFires';
    $query['fields'][] = 'SpecialOutsideFires';
    $query['fields'][] = 'CropFires';

    $table = 'firedata.Analysis_Fires_by_Zip_by_Type';

    if ( $query['fields'] ) {
        $fields = implode(", ", $query['fields']);
    } else {
        $fields = '*';
    }

    if( $query['state'] ){
        $state = "'".$query['state']."'";
    }

    if ( $query['zips'] && $query['state'] ){
        $zips   = "'".implode("','",$query['zips'])."'";
        $result = db_query('SELECT '.$fields.' FROM '.$table.' WHERE zip IN ('.$zips.') AND state = '.$state, array());
    } elseif ( $query['state'] ) {
        $result = db_query('SELECT '.$fields.' FROM '.$table.' WHERE state = '.$state, array());
    } else {
        $result = db_query('SELECT '.$fields.' FROM '.$table.' ', array());
    }

    $data = array();

    foreach ($result as $record) {
        $zip = "'".$record->zip."'";

        $geo = db_query('SELECT primary_city, latitude, longitude FROM firedata.zip_code_database  WHERE zip = '.$zip)->fetchObject();

        $feature = array();
        $feature['type'] = 'Feature';
        $feature['geometry'] = array();
        $feature['geometry']['type'] = "Point";
        $feature['geometry']['coordinates'] = array($geo->longitude,$geo->latitude);

        $feature['properties'] = array();
        $feature['properties']['name']       = $record->state;
        $feature['properties']['label']      = $geo->primary_city.' ('.$record->zip.')';
        $feature['properties']['totalFires'] = $record->TotalFires;

        $data[] = $feature;
    }

    return $data;
}